-- Library Book Management PostgreSQL schema
-- Run this after connecting to the database you want to use:
--   psql -U postgres -d library_book_management -f schema.sql

CREATE SCHEMA IF NOT EXISTS library;
SET search_path TO library, public;

CREATE TYPE book_status AS ENUM ('available', 'on_loan');

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL CHECK (btrim(title) <> ''),
    author VARCHAR(255) NOT NULL CHECK (btrim(author) <> ''),
    isbn VARCHAR(32) UNIQUE,
    publisher VARCHAR(255),
    category VARCHAR(150),
    year_published INTEGER CHECK (
        year_published IS NULL OR year_published BETWEEN 1 AND 9999
    ),
    status book_status NOT NULL DEFAULT 'available',
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(32) NOT NULL UNIQUE CHECK (btrim(student_id) <> ''),
    full_name VARCHAR(255) NOT NULL CHECK (btrim(full_name) <> ''),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE RESTRICT,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    issued_on DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    returned_on DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT loans_due_date_check CHECK (due_date >= issued_on),
    CONSTRAINT loans_returned_on_check CHECK (
        returned_on IS NULL OR returned_on >= issued_on
    )
);

-- A book can have many historical loans, but only one open loan at a time.
CREATE UNIQUE INDEX loans_one_open_loan_per_book
    ON loans (book_id)
    WHERE returned_on IS NULL;

CREATE INDEX books_title_search_idx ON books (lower(title));
CREATE INDEX books_author_search_idx ON books (lower(author));
CREATE INDEX books_category_idx ON books (category);
CREATE INDEX loans_issued_on_idx ON loans (issued_on);
CREATE INDEX loans_returned_on_idx ON loans (returned_on);
CREATE INDEX loans_member_idx ON loans (member_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER books_set_updated_at
BEFORE UPDATE ON books
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER members_set_updated_at
BEFORE UPDATE ON members
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER loans_set_updated_at
BEFORE UPDATE ON loans
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION sync_book_status()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    affected_book_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        affected_book_id := OLD.book_id;
    ELSE
        affected_book_id := NEW.book_id;
    END IF;

    UPDATE books
    SET status = CASE
        WHEN EXISTS (
            SELECT 1
            FROM loans
            WHERE loans.book_id = affected_book_id
              AND loans.returned_on IS NULL
        ) THEN 'on_loan'::book_status
        ELSE 'available'::book_status
    END
    WHERE books.id = affected_book_id;

    IF TG_OP = 'UPDATE' AND OLD.book_id <> NEW.book_id THEN
        UPDATE books
        SET status = CASE
            WHEN EXISTS (
                SELECT 1
                FROM loans
                WHERE loans.book_id = OLD.book_id
                  AND loans.returned_on IS NULL
            ) THEN 'on_loan'::book_status
            ELSE 'available'::book_status
        END
        WHERE books.id = OLD.book_id;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER loans_sync_book_status
AFTER INSERT OR UPDATE OR DELETE ON loans
FOR EACH ROW
EXECUTE FUNCTION sync_book_status();

-- API-friendly records for the Issued Books screen.
CREATE OR REPLACE VIEW issued_books AS
SELECT
    loans.id,
    books.id AS book_id,
    books.title,
    books.author,
    members.id AS member_id,
    members.full_name AS member,
    members.student_id,
    loans.issued_on,
    loans.due_date,
    CASE
        WHEN loans.due_date < CURRENT_DATE THEN 'Overdue'
        ELSE 'On loan'
    END AS status
FROM loans
JOIN books ON books.id = loans.book_id
JOIN members ON members.id = loans.member_id
WHERE loans.returned_on IS NULL;

-- API-friendly records for the Returned Books screen.
CREATE OR REPLACE VIEW returned_books AS
SELECT
    loans.id,
    books.id AS book_id,
    books.title,
    books.author,
    members.id AS member_id,
    members.full_name AS member,
    members.student_id,
    loans.issued_on,
    loans.returned_on,
    CASE books.status
        WHEN 'available' THEN 'Available'
        WHEN 'on_loan' THEN 'On loan'
    END AS status
FROM loans
JOIN books ON books.id = loans.book_id
JOIN members ON members.id = loans.member_id
WHERE loans.returned_on IS NOT NULL;

-- Catalog output matching the frontend's book fields.
CREATE OR REPLACE VIEW book_catalog AS
SELECT
    id,
    title,
    author,
    isbn,
    publisher,
    category,
    year_published,
    CASE status
        WHEN 'available' THEN 'Available'
        WHEN 'on_loan' THEN 'On loan'
    END AS status,
    description,
    created_at,
    updated_at
FROM books;